build: off

notifications:
  - provider: Webhook
    url:
      secure: zo4G8QEEhysMlbsS97YWUjKnB2hzs4ZXWdXfca22/L+m4/sBA/duv7FsPddwKjVT/TGfmQ+pwMAUj9hMByeRRl+oGN7aKal4gOjm7pzJSUg=
    headers:
      Authorization:
        secure: 4PqhloV2J8t5ZWSFOpPK4g==
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
